# Site settings
title: Wei Huo
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/touxiang.jpg'
bkimage: '/images/bk3.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Wei Huo'
  email: 3111314916@qq.com
  orcid: 0009-0003-1684-4873
  # twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  hw-star
  # linkedin_username:  111111
  # meetup_name: Azure-Meetup-Rostock-MV

skills:
  frontend:
    - Vue
    - JavaScript
    - CSS
    - ElementUI
  backend:
    - Java
    - SpringBoot
    - Redis
    - MySQL
  ai:
    - Python
    - PyTorch
  others:
    - Linux
    - Crawler
  
notes:
    - title: Java Learning Notes
      url: https://blog.csdn.net/weixin_45262946/article/details/128457373
    - title: Communication system based on Socket
      url: https://download.csdn.net/download/weixin_45262946/87764032
      
publications:
  - title: "STGAN: Swin Transformer-Based GAN to Achieve Remote Sensing Image Super-Resolution Reconstruction"
    authors: "Wei Huo, Xiaodan Zhang, Shaojie You, Yongkun Zhang, Qiyuan Zhang and Naihao Hu"
    venue: "arXiv 2024"
    demo: https://hw-star.github.io/STGAN
    pdf: "https://www.mdpi.com/2076-3417/15/1/305/pdf"
    code: "https://github.com/hw-star/STGAN"
  - title: "SMGAN: A Multi-Path Generative Adversarial Network for Remote Sensing Image Super-Resolution Reconstruction"
    authors: "Wei Huo, Xiaodan Zhang, Qiyuan Zhang and Naihao Hu"
    venue: "arXiv 2025"
    demo: https://hw-star.github.io/SMGAN
    pdf: ""
    code: "https://github.com/hw-star/SMGAN"

fun:
  - 🌌 I love stargazing in Xining's clear skies.
  - 🎮 Big fan of strategy games—especially Civilization VI.
  - 📷 Enjoy taking photos of landscapes and architecture.
  - 📚 Learning addict—frequently explore new topics in AI and philosophy.

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
